<section class="form-block">
    <h2>Connexion</h2>
    <form class="form" method="POST" action="index.php?route=connect">
        <div class="input-block">
            <input type="text" name="idAdmin" required><label for="idAdmin">Votre identifiant</label>
        </div>
        <div class="input-block">
            <input type="password" name="password" required><label for="password">Mot de passe</label>
        </div>
        <button class="btn" type="submit">GO!</button>
    </form>
</section>