<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Scoring-Smile-in-the-Light</title>
    <link rel="stylesheet" href="public/css/style.css" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.css" integrity="sha512-0nkKORjFgcyxv3HbE4rzFUlENUMNqic/EzDIeYCgsKa/nwqr2B91Vu/tNAu4Q0cBuG4Xe/D1f/freEci/7GDRA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" integrity="sha512-yVvxUQV0QESBt1SyZbNJMAwyKvFTLMyXSyBHDO4BG5t7k/Lw34tyqlSDlKIrIENIzCl+RVUNjmCPG+V/GMesRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav>
        <ul>
            
            <li><a href="index.php?route=logIn">Log-In</a></li>
            <li><a href="index.php?route=backSA">back SA</a></li>
            <?php if( isset( $_SESSION['admin'] ) ) : ?>
            <li><a href="index.php?route=backAE&adminID=<?= $_SESSION['admin']['admin_id'] ?>">back AE</a></li>
            <?php endif; ?>
            <?php if( isset( $_SESSION['admin'] ) || isset( $_SESSION['superAdmin'] ) ) : ?>
                <li><a href="index.php?route=disconnect">Déconnexion</a></li>
            <?php endif; ?>
        </ul>
    </nav>
    <?php include_once $view ?>
    <?php if( isset( $_GET['route'] ) && $_GET['route'] == "tournament") : ?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" integrity="sha512-rMGGF4wg1R73ehtnxXBt5mbUfN9JUJwbk21KMlnLZDJh7BkPmeovBuddZCENJddHYYMkCh9hPFnPmS9sspki8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.proto.min.js" integrity="sha512-jVHjpoNvP6ZKjpsZxTFVEDexeLNdWtBLVcbc7y3fNPLHnldVylGNRFYOc7uc+pfS+8W6Vo2DDdCHdDG/Uv460Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="public/js/tournament/tournament.js" type="module"></script>
    <?php endif; ?>
</body>
</html>


