<section class="tab-block">
    <h2><?= $event['event_name'] ?> : Liste des matchs</h2>
   
    <?php if( $resultat_first_turn == true ) : ?>
        <p><a href="index.php?route=rank&eventID=<?= $_GET['eventID'] ?>">Accéder au classement</a></p>
        <p><a href="index.php?route=nextTeamTurn&eventID=<?= $_GET['eventID'] ?>&turn=2">Générer le second tour</a></p>
    <?php elseif( $resultat_sec_turn == true ) : ?> 
        <p><a href="index.php?route=rank&eventID=<?= $_GET['eventID'] ?>">Accéder au classement</a></p>
        <p><a href="index.php?route=nextTeamTurn&eventID=<?= $_GET['eventID'] ?>&turn=3">Générer le troisième tour</a></p>
    <?php elseif( $resultat_third_turn == true ) : ?> 
        <p><a href="index.php?route=rank&eventID=<?= $_GET['eventID'] ?>">Accéder au classement</a></p>
        <p><a href="index.php?route=nextTeamTurn&eventID=<?= $_GET['eventID'] ?>&turn=4">Générer le quatrième tour</a></p>
    <?php elseif( $resultat_fourth_turn == true ) : ?> 
        <p><a href="index.php?route=rank&eventID=<?= $_GET['eventID'] ?>">Accéder au classement</a></p>
    <?php endif; ?>
    
    
    <?php foreach( $turns as $turn ) : ?>
        <?php if( !empty($turn) ) : ?>
            <table class="table-admin">
                <thead>
                    <tr>
                        <th>Tour</th>
                        <th>Player 1</th>
                        <th>Player 2</th>
                        <th>Score p1</th>
                        <th>Score p2</th>
                        <?php if( $turn[(count($turn) - 1)]['score_player_1'] == NULL && $turn[(count($turn) - 1)]['score_player_2'] == NULL ) : ?>
                            <th></th>
                        <?php endif; ?>
                        <th>Résultat</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach( $turn as $match ) : ?>
                        <tr>
                            <td><?= $match['match_sleeve'] ?></td>
                            <td>
                            <?php foreach( $users as $user ) : ?>
                                <?php if( $user['user_id'] == $match['player_1_user_id'] ) : ?>
                                    <?php $player_1 = $user['user_pseudo']; echo $player_1; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>   
                            </td>
                            <td>
                            <?php foreach( $users as $user ) : ?>
                                <?php if( $user['user_id'] == $match['player_2_user_id'] ) : ?>
                                    <?php $player_2 = $user['user_pseudo']; echo $player_2; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>   
                            </td>
                            <form method="POST" action="index.php?route=editScores&matchID=<?= $match['match_id'] ?>&eventID=<?= $_GET['eventID'] ?>">
                            <td>
                                <?php if( $match['score_player_1'] == NULL ) : ?>
                                    <input type="number" name="score-player-1" value="<?= $match['score_player_1'] ?>">
                                <?php else : ?>
                                    <?= $match['score_player_1'] ?>
                                <?php endif; ?>
                            </td>
                            <?php foreach( $users as $user ) : ?>
                                <?php if( $user['user_id'] == $match['player_1_user_id'] ) : ?>
                                    <?php $team_player_1 = $user['team_id']?>
                                    <input type="hidden" value="<?= $team_player_1 ?>" name="team-1">
                                    <input type="hidden" value="<?= $match['player_1_user_id'] ?>" name="user-id-1">
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <td>
                                <?php if( $match['score_player_2'] == NULL ) : ?>
                                    <input type="number" name="score-player-2" value="<?= $match['score_player_2'] ?>">
                                <?php else : ?>
                                    <?= $match['score_player_2'] ?>
                                <?php endif; ?>
                            </td>
                            <?php foreach( $users as $user ) : ?>
                                <?php if( $user['user_id'] == $match['player_2_user_id'] ) : ?>
                                    <?php $team_player_2 = $user['team_id']?>
                                    <input type="hidden" value="<?= $team_player_2 ?>" name="team-2">
                                    <input type="hidden" value="<?= $match['player_2_user_id'] ?>" name="user-id-2">
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php if( $match['score_player_1'] == NULL && $match['score_player_2'] == NULL ) : ?>
                                <td><input type="submit" value="éditer"></td>
                            <?php endif; ?>
                            </form>
                            <?php if( $match['match_exaequo'] == 1 ) : ?>
                                <td>Egalité</td>
                            <?php elseif( $match['match_winner'] == 1 ) : ?>
                                <td><?= $player_1 ?></td>
                            <?php elseif( $match['match_winner'] == 2 ) : ?>
                                <td><?= $player_2 ?></td>
                            <?php else : ?>    
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>    
        <?php endif; ?>
    <?php endforeach; ?>   
</section> 